### ISSUE TITLE
How to run demo sveltekit svelte-lexical ?

### ISSUE THREAD

**Issue by ProtonBeamCannon** [umaranis/svelte-lexical#91]
Hi @umaranis I want to try out svelte-lexical and try to run the demo, for sveltekit but I keep getting this error
![image](https://github.com/user-attachments/assets/0bd02fb3-80c6-4827-bc45-6201ba595674)

Error: Failed to resolve entry for package "svelte-lexical". The package may have incorrect main/module/exports specified in its package.json.

What should I do here ? I made sure I ran npm i svelte-lexical, so what am i missing

**Comment by umaranis** [comment]
Hi @ProtonBeamCannon ,
Have you build the ‘svelte-lexical’ package before running the demo project?

Please have a look at ‘getting started’ section in the ReadMe file. Do let me know if you still face any issues? Thanks.

**Comment by ProtonBeamCannon** [comment]
I tried it again, i followed the read.me and i run the demo playground and demo sveltekit and still got the same error

**Comment by umaranis** [comment]
Hi @ProtonBeamCannon ,
I have just tried on a fresh clone. The build process is broken with `npm` but works fine with 'pnpm`. It has also happened a few times in the past as well due to the ESM and CommonJS mess.

I will look into the recent package upgrades to find the culprit.

**Comment by umaranis** [comment]
Hi @ProtonBeamCannon ,
I have pushed a fix on [npm-build](https://github.com/umaranis/svelte-lexical/tree/npm-build) branch.

Could you confirm if it resolves the issue?

**Comment by ProtonBeamCannon** [comment]
Did it resolve for you ?
I created a fresh clone, pick hte npm-build branch, go to the cd packages/svelte-lexical, npm i, npm run build,
I tried to go to the demos playground and sveltekit and npm run dev. but still get the same error, after that i tried run npm install and its the same, 
I tried to npm run build on demos/sveltekit and i got this
![image](https://github.com/user-attachments/assets/40ca90a1-69d6-4a7c-a4d5-3cf85d94e417)

Maybe this is a clue? 
My node v20.6.1 if this matters, also this is the package.json
![image](https://github.com/user-attachments/assets/7073f99e-5f5e-4d62-a21a-1f8114a65e2e)

**Comment by umaranis** [comment]
Hi @ProtonBeamCannon ,
yes, 'npm-build` branch resolves the issue for me.

My node version is `22.5.1`.

Are you able to upgrade to this version and test?

**Comment by umaranis** [comment]
Here is my output for the same command
![image](https://github.com/user-attachments/assets/fa1b7161-b9f0-4b9b-a31e-c6b312e400da)


I would appreciate it if you could upgrade your node to `22.5.1`

**Comment by ProtonBeamCannon** [comment]
Hi, sorry responding so late, i upgrade the node to v22.5.1
![image](https://github.com/user-attachments/assets/fce40aed-abf7-4ffb-adfb-d76a96ffd98d)

I tried both npm and pnpm in the folder svelte-lexical and svelte-lexical/demo/sveltekit , it didnt work

![image](https://github.com/user-attachments/assets/b2b701c6-228e-4e6e-becc-a34a200ba417)

**Comment by umaranis** [comment]
This is strange.

Could you share the full output of all the commands you are running? For instance, `pnpm i`, `pnnpm build` and `pnpm dev` from the `packages/svelte-lexical` directory. @ProtonBeamCannon

**Comment by ProtonBeamCannon** [comment]
![image](https://github.com/user-attachments/assets/9e1085ab-b5cd-4989-aebe-c92898fe62b2)

![image](https://github.com/user-attachments/assets/e46d5d0a-acc8-4d66-9b46-3c78c54bd6f2)




`error during build:
[commonjs--resolver] Failed to resolve entry for package "svelte-lexical". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///C:/Users/user/Desktop/Prog/Lexical/svelte-lexical/node_modules/.pnpm/vite@5.3.3_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:47164:15)
    at resolvePackageEntry (file:///C:/Users/user/Desktop/Prog/Lexical/svelte-lexical/node_modules/.pnpm/vite@5.3.3_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:47161:3)
    at tryNodeResolve (file:///C:/Users/user/Desktop/Prog/Lexical/svelte-lexical/node_modules/.pnpm/vite@5.3.3_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46977:16)
    at Object.resolveId (file:///C:/Users/user/Desktop/Prog/Lexical/svelte-lexical/node_modules/.pnpm/vite@5.3.3_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46727:19)
    at Object.handler (file:///C:/Users/user/Desktop/Prog/Lexical/svelte-lexical/node_modules/.pnpm/vite@5.3.3_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:65948:15)
    at file:///C:/Users/user/Desktop/Prog/Lexical/svelte-lexical/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:19778:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///C:/Users/user/Desktop/Prog/Lexical/svelte-lexical/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:19678:28)
    at async resolveId (file:///C:/Users/user/Desktop/Prog/Lexical/svelte-lexical/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:18359:26)
    at async ModuleLoader.resolveId (file:///C:/Users/user/Desktop/Prog/Lexical/svelte-lexical/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:18762:15)
    at async Object.resolveId (file:///C:/Users/user/Desktop/Prog/Lexical/svelte-lexical/node_modules/.pnpm/vite@5.3.3_@types+node@20.12.8/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:12701:10)
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by umaranis** [comment]
Hi @ProtonBeamCannon ,

As I requested, could you please run these commands from the `packages/svelte-lexical` folder (not `demos/sveltekit`)?

**Comment by ProtonBeamCannon** [comment]
Hi sorry for the late  reply, yes what i meant was i tried everything but of course i tried to follow your instruction that i go to `packages/svelte-lexical`  and then `npm install` then `npm run build` after that  i got this error
![image](https://github.com/user-attachments/assets/ed4b7595-130a-4483-8876-3efe58eac9c2)

after that i went to `demos/playground` and stated in your readme.md and try `npm run dev` but the i got the error.

Can you show me an example of it working in Stackblitz so that  we can debug this in the same environment together?

**Comment by umaranis** [comment]
Hi @ProtonBeamCannon ,

Here is the StackBlitz for `demos/playground`:

https://stackblitz.com/~/github.com/umaranis/svelte-lexical/tree/stackblitz-playground?view=editor

Have a look at `.stackblitzrc` file for the start command (the branch is `stackblitz-playground`).

**Comment by MattBrittan** [comment]
@ProtonBeamCannon hit the same issue - fixed by editing `packages/svelte-lexical/package.json`, change:

```"build": "vite build && pnpm package",```

to

```"build": "vite build && npm run package",```

`package.json` assumes that pnpm` is installed, so another option would be to install it.
